### ISSUE TITLE
Rajout concernant les ordiphones

### ISSUE THREAD

**Issue by phvialle** [LINCnil/Recommandations-pour-le-teletravail#2]
Rajouter :
Si vous utilisez votre smartphone personnel dans le cadre du travail,  pensez également à le sécuriser : mettre un code pin, vérifier et installer les mises à jour du système, désactiverl les dépôts non officiels, pas de jailbreak, etc 
Vous pouvez également suivre ce guide, plutôt complet : https://www.frandroid.com/culture-tech/securite-applications/651369_comment-securiser-votre-smartphone-votre-tablette-ou-votre-pc

**Comment by LaboCNIL** [comment]
Bonjour et merci pour vos retours.

En conséquence, nous avons ajouté une partie spécifique aux téléphones sur les recommandations.

Cordialement.
